[versions]
# libraries
activity-compose = "1.9.1" # 7/31/24
appcompat = "1.7.0" # 7/7/24
browser = "1.8.0" # 7/7/24
compose = "1.6.8" # 7/7/24
compose-bom = "2024.06.00" # 7/9/24
coreKtx = "1.13.1" # 7/7/24
gson = "2.10.1" # 7/7/24
junit = "4.13.2" # 7/7/24
material3 = "1.2.1" # 7/7/24
mockk = "1.13.11" # 7/7/24
navigation-compose = "2.7.7" # 7/7/24
ostermiller = "1.07.00" # 7/21/24
ui-test-junit4 = "1.6.8"
# gradle/language
agp = "8.5.1" # 7/13/24
kotlin = "2.0.0" # 7/7/24
ktlint = "11.3.1" # 7/21/24

[libraries]
# androidx
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name ="ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui-test-junit4" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
# com.google
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
# unit testing
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
# misc
ostermiller-util = { module = "org.ostermiller:utils", version.ref = "ostermiller" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }